// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations (direct connection, port 5432).
    // Falls back to DATABASE_URL if DIRECT_URL is not set.
    url: env("DIRECT_URL") ?? env("DATABASE_URL"),
  },
});
